services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql  # this saves DB data

  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data  # this saves Redis data

  web:
    build: .
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - mysql
      - redis

volumes:  # ADD THIS AT THE BOTTOM
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge